### PR TITLE
Small fix

### PR DESCRIPTION
**Pull request by Fedorito**

### CODE REVIEW

**Comment by amphoracheats** [comment]
What does that fix actually?

**Comment by Fedorito** [comment]
> What does that fix actually?

#43 
Toggles off crashing asus props if transparency = 100

**Comment by amphoracheats** [comment]
> > What does that fix actually?
> 
> #43
> Toggles off crashing asus props if transparency = 100

Well, if prop transparency is at 100 percent then it should just remove them, why remove this check, i dont have any crashes at 100 percent even with the check.

**Comment by Fedorito** [comment]
> > > What does that fix actually?
> > 
> > 
> > #43
> > Toggles off crashing asus props if transparency = 100
> 
> Well, if prop transparency is at 100 percent then it should just remove them, why remove this check, i dont have any crashes at 100 percent even with the check.

But i have, and some people have too.
I think this fix will fix some crashes

**Comment by Fedorito** [comment]
And this fix cant do this hack worse than now

**Comment by amphoracheats** [comment]
> And this fix cant do this hack worse than now

This sentence didnt make sense, ill pretend that i didnt read that

**Comment by Fedorito** [comment]
> > And this fix cant do this hack worse than now
> 
> This sentence didnt make sense, ill pretend that i didnt read that

:((((((

**Comment by alpine971** [comment]
I don't see what you're trying to do with this.

**Comment by EternityX** [comment]
Are you using the latest changes to the branch (specifically 9bd1130f1e0d800edae9f88fb2107ac2577d9523)? One of the changes there may fix the issue.

**Pull request closed without merging**
