### PR TITLE
Anti-aimbot 

### PR DESCRIPTION
**Pull request by Fedorito**

### CODE REVIEW

**Comment by alpine971** [comment]
Sorry, what you did still doesn't meet project standards, we appreciate your will to help, we just want the project to be well organized.

**Comment by Fedorito** [comment]
> Sorry, what you did still doesn't meet project standards, we appreciate your will to help, we just want the project to be well organized.

You can change it, if you dont like it

**Comment by alpine971** [comment]
> > Sorry, what you did still doesn't meet project standards, we appreciate your will to help, we just want the project to be well organized.
> 
> You can change it, if you dont like it

We're trying to write a new anti aim system later, I suggest you look at how other cheats did theirs so maybe you can improve your code :)

**Comment by Fedorito** [comment]
> > > Sorry, what you did still doesn't meet project standards, we appreciate your will to help, we just want the project to be well organized.
> > 
> > 
> > You can change it, if you dont like it
> 
> We're trying to write a new anti aim system later, I suggest you look at how other cheats did theirs so maybe you can improve your code :)

But my code is better than nothing, you can add better code later

**Pull request closed without merging**
