### PR TITLE
edit fakelag

### PR DESCRIPTION
**Pull request by TXIuTnVsbA**
disable fakelag(choke=1;= =I can only do that) when i enable the mic or fight

### CODE REVIEW

**Comment by EternityX** [comment]
You do not need keystate.h
use 
```c
g_input.key_pressed( virtual_key_code )
```

This is also not a proper fix for voice chat whilst using fakelag.

**Comment by TXIuTnVsbA** [comment]
> You do not need keystate.h
> use
> 
> ```c
> g_input.key_pressed( virtual_key_code )
> ```
> 
> This is also not a proper fix for voice chat whilst using fakelag.

= =ok

**Comment by alpine971** [comment]
Engine -> IsVoiceTransmitting or something like that to see if you’re talking in game

**Comment by TXIuTnVsbA** [comment]
> Engine -> IsVoiceTransmitting or something like that to see if you’re talking in game

my bad = =;

**Comment by TXIuTnVsbA** [comment]
> Engine -> IsVoiceTransmitting or something like that to see if you’re talking in game



> You do not need keystate.h
> use
> 
> ```c
> g_input.key_pressed( virtual_key_code )
> ```
> 
> This is also not a proper fix for voice chat whilst using fakelag.

i have more change, can i requests again?

bug1
bug2
bug4
bug3

**Comment by alpine971** [comment]
If you want to, if the changes meet the project’s code standard they will be accepted.

**Comment by TXIuTnVsbA** [comment]
> If you want to, if the changes meet the project’s code standard they will be accepted.

thanks you

**Pull request closed without merging**
