### PR TITLE
Stop destroying games for everyone, asshole!

### PR DESCRIPTION
**Pull request by cheaterbastard**

### CODE REVIEW

**Comment by Patoke** [comment]
kys

**Comment by cheaterbastard** [comment]
Bastard cheater

**Comment by Patoke** [comment]
It's not a project public to shitty pasters, u gotta fix it urself and use knowledge, so not every kid can use this, now go kys

**Comment by cheaterbastard** [comment]
Learn english mate.

**Comment by Patoke** [comment]
Get coding knowledge mate.

**Comment by EternityX** [comment]
This is not a project available for your average **unintelligent** cheater. This is for people willing to learn more about game hacking and how it works specific to the Source engine.

**Comment by software-engineer0** [comment]
As one of the retainers for the repository, I have a few things to clear up for you:

* This is an outdated repository, and much of what needs to be replaced requires knowledge of the game, IDA thereof to fix.

* The precompiled binaries for the cheat are not available on the repository for users to use.

* Many of the features within the source code are incomplete and lacking in the retrospective counterparts.

This source code was made solely for recreational purposes and as a hobby, and the release of this source code did not come with the intention to ruin the game on a competitive level for players of Counter-Strike: Global Offensive.

To infer from prior posts, the cheat is also detected and would result in a ban from VAC secure servers probably even before a game finishes.

Kind regards,
software engineer.

**Comment by cheaterbastard** [comment]
You make things worse. People using cheat code hosted on GitHub, modify it and the game starts all over again. 

Maybe think about what damage you do by hosting anything related to cheating or bypassing VAC/Games. Incomplete or not, it allows anyone to get insight into how this can work.

**Comment by software-engineer0** [comment]
The source code WAS, and I repeat, WAS solely for recreational purposes and to demonstrate how easy it is ro manipulate the game.

In releasing this source code, the intention was to bring these major flaws to attention and to demonstrate how said effect is achieved.

The cheat itself is unusable and the "average" person could not use it in the first place, and because of this I see no problem releasing it to bring the major flaws within the game.

If you have a problem with the GitHub, feel free to browse elsewhere.

Have a nice day!

**Comment by cheaterbastard** [comment]
If it's unfinished or not working anymore then remove it.

**Comment by cheaterbastard** [comment]
Cheating is not allowed, you know that, spreading your fucking repo will help any motherfucking cheater, which is your fucking plan.

**Comment by EternityX** [comment]
This is not a valid pull request. Please move this discussion to the [issues page](https://github.com/EternityX/DEADCELL-CSGO/issues).

**Pull request closed without merging**
