### PR TITLE
Fix std::sort comparison predicate causing assertion failure

### PR DESCRIPTION
**Pull request by danielkrupinski**

### CODE REVIEW

**Comment by alpine971** [comment]
do you know what this happens in the first place?

**Comment by EternityX** [comment]
This change alone will prevent the aimbot from shooting targets unless one of the priority conditions are met.

**Comment by danielkrupinski** [comment]
It does not influence sorting results. Former comparison (`>=`) doesn't meet [C++ requirements](https://en.cppreference.com/w/cpp/named_req/Compare) therefore causes debug assertion failure.

**Comment by EternityX** [comment]
Thanks. I never noticed the assertion because I was using release builds.
However this is no longer an issue due to the removal of record sorting.

**Pull request closed without merging**
